### PR TITLE
file: data loss prevention in mapped file

### PR DESCRIPTION
**Pull request by leonardo-albertovich**
This PR addresses the part of fluent-bits issue [5378](https://github.com/fluent/fluent-bit/issues/5378). 

The root of the issue is that when bringing a chunk up `mmap_file` rounds the file size up to a multiple of the systems page size but does not resize the file before which causes any data located after the real end of the file to be lost.

The easiest way to reproduce this issue is to : 

1. Create a stream
2. Create 64 chunks and leave them open
3. Create one more chunk
4. Bring the chunk up (it will be down because `max_chunks_up` defaults to 64)
5. Write data to the newly created chunk
6. Set the chunk down

_This is an explanation of how fluent-bit triggers the issue_

This will cause data to be lost because when the 65th chunk is created by `cio_file_open` `open_and_up` will return false which will cause the newly created chunk not to be mapped. 

Then, in fluent-bits case `flb_input_chunk_create` will notice the chunks original state is `DOWN` so it will bring the chunk up to write the headers before setting it down once again.

When the chunk is set down its size is trimmed so no disk space is wasted which means the size goes from `one * page size` (or 4kb in most systems) to the raw size which would be something around `24 + tag length` bytes.

Then `input_chunk_append_raw` will want to append the data to the chunk but since it's down it will do the same UP -> WRITE -> DOWN cycle, except this time `mmap_file` will round up the file size before using it to map the file (and most importantly set the reported allocated size). 

Because the real file is lower than 4kb (`one * page size`) the size will be artificially increased without actually changing the file size and in cases where the data fluent-bit tries to append is smaller than the "available" size it will just write past the actual end of the file.

Credit for finding the true root of the issue goes to @matthewfala as I had found the right symptom and a practical correction but missed the wrong calculation thus missing the true origin and thought the issue could be related to a corner case in EKSs mount point system.

### CODE REVIEW

**Comment by matthewfala** [comment]
I think this shouldn't be needed with the other PR we merged in right?

**Comment by matthewfala** [comment]
https://github.com/edsiper/chunkio/pull/80

**Comment by matthewfala** [comment]
So what I mean is we resolved the problems on master so the down up append down up data loss problem should not need to be fixed again. The rest of the pr is probably needed

**Comment by leonardo-albertovich** [comment]
> So what I mean is we resolved the problems on master so the down up append down up data loss problem should not need to be fixed again.

I think you're right, according to the man page `len` doesn't need to be a multiple of the systems page size (`addr` and `off` do but not `len), do you think there could be any problems with that change? I could change the PR to null that one if needed.

Sorry, I got it messed up due to working with 1.8 which is still on an older version.

**Comment by leonardo-albertovich** [comment]
I'd still go ahead with the PR not because of that but because it fixes some silly prototype definition issues and a bug in a test case so there's a value on it but yeah, it's definitely not crucial.

**Comment by matthewfala** [comment]
Wait @edsiper, I thought you said in #80 that we  want to keep mmaps at page-size multiples because there is some benefit to that? (this is why we chose solution 1 over solution 2)

**Comment by matthewfala** [comment]
https://github.com/edsiper/chunkio/pull/80#issuecomment-1069775101

**Comment by matthewfala** [comment]
It's probably fine. With the next append we'll increase filesize and remap the file anyways, so probably the performance benefits are not realized. (not sure what those benefits even would be)

**Comment by leonardo-albertovich** [comment]
I have no idea, I saw in a response in #80 that he mentioned line 364 being obsolete so I think it could have been a misunderstanding.

**Comment by matthewfala** [comment]
I followed up on slack... @edsiper wanted to stick with solution 1 (with solution 1, solution 2 is not needed and we can keep mmappings at always multiples of page size).

He thought there was performance benefits to mapping page size multiples, but couldn't remember what they were. (not sure if this is low level, because the operating system benefits by aligning mmap's to multiples of page size, and offsetting means that some pages will be kept open while unmapping part of the page)

**Pull request merged**
